name: Build on PR

on:
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Grant execute permission for buildImage
        run: chmod +x buildImage.sh

      - name: Grant execute permission for mainApp/buildImage
        run: chmod +x mainApp/buildImage.sh

      - name: Build
        id: build-image
        run: |
          ./buildImage.sh